{"name": "test_add_contact_to_group", "status": "failed", "statusDetails": {"message": "AssertionError: assert 368:name:headerQY|r.BV1X )wa~*7`:footerx] u~KaJN3l in []\n +  where [] = <bound method get_groups_for_contact of <fixture.orm.ORMFixture object at 0x00000191926A0A60>>(324:firstnamesdpd:lastname=ZS7)\n +    where <bound method get_groups_for_contact of <fixture.orm.ORMFixture object at 0x00000191926A0A60>> = <fixture.orm.ORMFixture object at 0x00000191926A0A60>.get_groups_for_contact", "trace": "app = <fixture.application.Application object at 0x0000019192632CD0>\normdb = <fixture.orm.ORMFixture object at 0x00000191926A0A60>\n\n    def test_add_contact_to_group(app, ormdb):\n        # проверка предусловий\n        if len(ormdb.get_contact_list()) == 0:\n            app.contact.create(Contact(firstname=\"test\"))\n        if len(ormdb.get_group_list()) == 0:\n            app.group.create(Group(name=\"test\"))\n        exception_group_list = []\n        contact = random.choice(ormdb.get_contact_list())\n        list_groups_for_contact = ormdb.get_groups_for_contact(contact)\n        list_all_groups = ormdb.get_group_list()\n        for g in list_all_groups:\n            if g not in list_groups_for_contact:\n                exception_group_list.append(g)\n        if len(exception_group_list) == 0:\n            group = list_groups_for_contact[random.randrange(len(list_groups_for_contact))]\n            app.contact.remove_from_group(contact, group)\n        else:\n            index = random.randrange(len(exception_group_list))\n            group = list_all_groups[index]\n        app.contact.add_contact_to_group(contact, group)\n        # проверяем, что контакт добавлен в группу\n>       assert group in ormdb.get_groups_for_contact(contact)\nE       assert 368:name:headerQY|r.BV1X )wa~*7`:footerx] u~KaJN3l in []\nE        +  where [] = <bound method get_groups_for_contact of <fixture.orm.ORMFixture object at 0x00000191926A0A60>>(324:firstnamesdpd:lastname=ZS7)\nE        +    where <bound method get_groups_for_contact of <fixture.orm.ORMFixture object at 0x00000191926A0A60>> = <fixture.orm.ORMFixture object at 0x00000191926A0A60>.get_groups_for_contact\n\ntest\\test_add_contact_to_group.py:28: AssertionError"}, "start": 1618131531758, "stop": 1618131533325, "uuid": "4f90f490-1d23-4f46-b840-85343c1a0612", "historyId": "38ec08ef9d40e9a5f581571d44033af1", "testCaseId": "b58c1d2cb321cd388e9abc3e2a2a5c12", "fullName": "test.test_add_contact_to_group#test_add_contact_to_group", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_add_contact_to_group"}, {"name": "host", "value": "DESKTOP-9MR3F4L"}, {"name": "thread", "value": "7688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_add_contact_to_group"}]}